# Initialization
base_dir: "."
metadata: "metadata.tsv"
pipeline_dir: "/gladstone/ott/home/izheludev/denim/pipeline"
paired: TRUE

# Pipeline mode
embedding: "ALL"  # can be: RTD or CGR or ALL

# Computational parameters
threads: 64

# Embedding paramters
strand: "forward"

# RTD parameters
k: 2
alphabet: "A C G T"

# Clustering parameters
min_cluster_size: 400
min_samples: 5
max_GMM: 5
seed: 42

# Bootstrapping parameters
n_bootstraps: 1000

# Sleuth parameters
parameter: "strain"
pseudocount: 0.5
alpha: 0.05
foldchange: 10
